FROM eclipse-mosquitto:latest

RUN apk update && \
    apk add --no-cache python3 py3-pip nano && \
    ln -sf python3 /usr/bin/python && \
    pip install --break-system-packages paho-mqtt requests

COPY mosquitto.conf /mosquitto/config/mosquitto.conf

EXPOSE 1883
EXPOSE 9001

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
